"""
Django settings for djangoProject8 project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
"""
Django settings for djangoProject8 project.
"""

from datetime import timedelta
from pathlib import Path
import os
from logging.handlers import RotatingFileHandler
from dotenv import load_dotenv
import environ

load_dotenv(".venv/.env")
BASE_DIR = Path(__file__).resolve().parent.parent

print(Path(__file__).resolve().parent.parent / 'django.log')

env = environ.Env(DEBUG=(bool, False))
env.read_env(BASE_DIR / '.env')

SECRET_KEY = env('SECRET_KEY', default='your-fallback-secret-key')
DEBUG = env.bool('DEBUG', default=False)

# CORS настройки
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_CREDENTIALS = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]']

# Настройки безопасности
SECURE_SSL_REDIRECT = False  # Отключаем принудительное перенаправление на HTTPS
SECURE_HSTS_SECONDS = 0  # Отключаем HSTS в режиме разработки
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # Отключаем HSTS для поддоменов
SECURE_HSTS_PRELOAD = False  # Отключаем предзагрузку HSTS
SECURE_PROXY_SSL_HEADER = None  # Отключаем проверку SSL-заголовков
SECURE_CONTENT_TYPE_NOSNIFF = True  # Запрещаем браузеру угадывать MIME-типы
SECURE_BROWSER_XSS_FILTER = True  # Включаем XSS-фильтр браузера
X_FRAME_OPTIONS = 'DENY'  # Запрещаем встраивание сайта в iframe

# Настройки куки
SESSION_COOKIE_SECURE = False  # Разрешаем куки без HTTPS
CSRF_COOKIE_SECURE = False  # Разрешаем CSRF куки без HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # Ограничиваем кросс-сайтовые запросы
CSRF_COOKIE_SAMESITE = 'Lax'  # Ограничиваем кросс-сайтовые запросы
SESSION_COOKIE_HTTPONLY = True  # Запрещаем доступ к куки через JavaScript
CSRF_COOKIE_HTTPONLY = True  # Запрещаем доступ к CSRF куки через JavaScript

# Настройки базы данных
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
        'OPTIONS': {
            'client_encoding': 'UTF-8',
        }
    }
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'csp',
    'corsheaders',
    'mydogs.apps.MydogsConfig',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'mydogs.middleware.csp_middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Перемещаем CORS middleware выше
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = ['127.0.0.1']

# CSP настройки
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "https://cdn.jsdelivr.net", "http://localhost:3000", "'unsafe-inline'")
CSP_STYLE_SRC = ("'self'", "https://cdn.jsdelivr.net", "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", "data:", "http://localhost:3000")
CSP_FONT_SRC = ("'self'", "https://cdn.jsdelivr.net")
CSP_CONNECT_SRC = ("'self'", "http://localhost:3000", "http://127.0.0.1:8000")
CSP_INCLUDE_NONE_IN = ['script-src', 'style-src']

ROOT_URLCONF = 'djangoProject8.urls'

# Настройки шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'build'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject8.wsgi.application'

# Настройки REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# Настройки паролей
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Локализация
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Minsk'
USE_I18N = True
USE_TZ = True

# Настройки статических файлов
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'build/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Настройки React
REACT_APP_DIR = os.path.join(BASE_DIR, 'build')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки логирования
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            'maxBytes': 5242880,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',  # Changed from DEBUG to INFO
            'class': 'logging.StreamHandler',
            'formatter': 'simple',  # Changed to simple formatter
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',  # Changed from DEBUG to INFO
            'propagate': True,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Пользовательские настройки
API_BASE_URL = "http://127.0.0.1:8000"