# Generated by Django 5.1.1 on 2024-10-31 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydogs',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='mydogs',
            name='content',
        ),
        migrations.RemoveField(
            model_name='mydogs',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='mydogs',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='mydogs',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='mydogs',
            name='title',
        ),
        migrations.AddField(
            model_name='mydogs',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mydogs',
            name='breed',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='mydogs',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mydogs.category'),
        ),
        migrations.AddField(
            model_name='mydogs',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='mydogs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
