# Generated by Django 5.1.3 on 2025-04-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydogs', '0002_remove_mydogs_cat_remove_mydogs_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydogs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mydogs.category'),
        ),
    ]
