# Generated by Django 5.1.3 on 2025-05-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydogs', '0003_alter_mydogs_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
