# Generated by Django 5.1.3 on 2025-05-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydogs', '0005_mydogs_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
