# Generated by Django 5.1.3 on 2025-06-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydogs', '0006_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dogs_images/'),
        ),
    ]
