# Generated by Django 5.1.3 on 2025-06-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydogs', '0009_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='mydog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to='mydogs.mydogs'),
        ),
    ]
