# Generated by Django 5.1.3 on 2025-06-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydogs', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydogs',
            name='gender',
            field=models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], default='male', max_length=6, verbose_name='Пол'),
        ),
    ]
