# Generated by Django 5.1.3 on 2025-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydogs', '0013_client_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='pending', max_length=32),
        ),
    ]
